import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Person",
              "name": "Adebayo ADEDEJI",
              image: "https://theebayo.name.ng/avatar.jpg",
              "alternateName": ["Theebayo", "Theebayo dev", "Adebayodv"],
              "jobTitle": "Full-Stack JavaScript Developer",
              "url": "https://theebayo.name.ng",
              "sameAs": [
                "https://x.com/theebayo",
                "https://linkedin.com/in/theebayo",
                "https://github.com/adebayo-jzs"
              ],
              "knowsAbout": [
                "Next.js",
                "React",
                "Node.js",
                "Tailwind CSS",
                "Frontend Development",
                "Backend Development",
                "Web Applications"
              ]
            }),
          }}
        />

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
