"use client"
import { Analytics } from "@vercel/analytics/next";
import { Geist, Geist_Mono } from "next/font/google"; 
import CursorWrapper from "@/components/CursorWrapper";
import React,{useState,useEffect} from "react";
import { North } from "@mui/icons-material";

import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [scrollProgress,setScrollProgress] = useState(0);
  // const scrollRef = useRef(null);

  useEffect(() => {
		const handleScroll = () => {
			const totalScroll = document.documentElement.scrollTop;
			const windowHeight = document.documentElement.scrollHeight - document.documentElement.clientHeight;
			const scroll = `${totalScroll / windowHeight}`;
			setScrollProgress(Number(scroll)); 
		}
		window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Person",
              "name": "Adebayo ADEDEJI",
              image: "https://theebayo.name.ng/avatar.jpg",
              "alternateName": ["Theebayo", "Adedeji Adebayo", "Adebayodv"],
              "jobTitle": "FullStack JavaScript Developer",
              "description":"Fullstack Javascript developer skilled in Next.Js,React,Node.js and modern javascript technologies",
              "url": "https://theebayo.name.ng",
              "image": "https://theebayo.name.ng/avatar.jpg",
              "sameAs": [
                "https://x.com/theebayo",
                "https://linkedin.com/in/theebayo",
                "https://github.com/adebayo-jzs"
              ],
              "socialLinks": [
                "https://x.com/theebayo",
                "https://linkedin.com/in/theebayo",
                "https://github.com/adebayo-jzs"
              ],
              "knowsAbout": [
                "Next.js",
                "React",
                "Javascript",
                "Node.js",
                "Tailwind CSS",
                "Frontend Development",
                "Backend Development",
                "Web Applications"
              ],
              "skills": [
                "Next.js",
                "Javascript",
                "React",
                "Node.js",
                "Tailwind CSS",
                "Frontend Development",
                "Backend Development",
                "Web Applications"
              ]
            }),
          }}
        />

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Analytics> */}
        <CursorWrapper className="mix-blend-difference">
          <Navbar/>
          {children}
          <Footer/>
        </CursorWrapper>
        <Analytics/>

        <div className="block fixed bottom-8 right-3 mix-blend-difference z-50">
        <div className="flex flex-col items-center gap-6">
          <span className="[writing-mode:vertical-rl] text-[11px] font-black tracking-[0.6em] text-white uppercase">SCROLL TO EXPLORE</span>
          <div className="h-16 w-[2px] bg-white/20 relative overflow-hidden">
            <div 
              className="absolute top-0 left-0 w-full bg-white transition-all duration-100 ease-out" 
              style={{ height: `${scrollProgress * 100}%` }}
            ></div>
          </div>
        </div>
        <button
          onClick={() =>
            window.scrollTo({ top: 0, behavior: "smooth" })
          }
          className="border rounded-full p-2 mt-3"
        >
          <North/>
        </button>

      </div>
      </body>
    </html>
  );
}
