export const projects = [
  {
    id: 1,
    projectname: "PageForge",
    desc: "Transform your product ideas into high-conversion landing pages in seconds using Gemini AI. No coding required.",
    tools: ["NextJS","Typescript", "Tailwind", "Vanilla CSS", "MongoDB", "Node.js","Gemini API"],
    preview: "https://pageforge-nu.vercel.app",
    // code: "https://github.com/adebayo-jzs/incognito",
    imgurl: "/pageforge.png",
    type: "Web Application",
    year: 2026,
  },
  {
    id: 2,
    projectname: "Textcognito",
    desc: "Textcognito is an anonymous messaging website where users can create unique links to receive anonymous messages from their friends.",
    tools: ["NextJS", "Tailwind", "Vanilla CSS", "Supabase", "Node.js"],
    preview: "https://textcognito.click",
    // code: "https://github.com/adebayo-jzs/incognito",
    imgurl: "/textcognito.png",
    type: "Web Application",
    year: 2026,
  },
  {
    id: 3,
    projectname: "Arecnime",
    desc: "Arecnime is an anime discovery and recommendation website designed to reimagine the anime browsing experience for anime lovers",
    tools: ["TAilwind", "CSS", "Javascript"],
    preview: "https://arecnime.vercel.app",
    // code: "https://github.com/adebayo-jzs/arecnime",
    imgurl: "/anime.png",
    type: "Website",
    year: 2026,
  },
  {
    id: 4,
    projectname: "Tourtech Admin Dashboard",
    desc: "Overview and analytics dashboard for an industrial visit planning and booking system for a school project",
    tools: ["NextJS", "Tailwind", "Vanilla CSS", "Supabase", "Node.js"],
    // preview: "https://tourtech.name.ng/admin",
    code: "https://github.com/adebayo-jzs/tourtech",
    imgurl: "/admindash.jpg",
    type: "Web Application",
    year: 2025,
  },
  {
    id: 5,
    projectname: "Fuelping",
    desc: "Community-driven real-time fuel price updates at nearby stations in Nigeria",
    tools: ["React", "Typescript", "Tailwind", "Supabase"],
    preview: "https://fuelping.vercel.app",
    code: "https://github.com/adebayo-jzs/fuelping",
    imgurl: "/fuelping.png",
    type: "Website",
    year: 2026,
  },
  {
    id: 6,
    projectname: "Personal Blog",
    desc: "Personal Developer blog built with supabase fully optimisized for Search Engines ",
    tools: ["React", "Tailwind", "Typescript", "Supabase"],
    preview: "https://blog.theebayo.name.ng",
    code: "https://github.com/adebayo-jzs/nextblog",
    imgurl: "/blog.jpg",
    type: "Web Application",
    year: 2025,
  },

  {
    id: 7,
    projectname: "Basic Weather App",
    desc: "A basic weather app built with Open Weather API for checking 24 hours weather forecast for various locations ",
    tools: ["HTML", "CSS", "Javascript"],
    preview: "https://adebayo-jzs.github.io/weatherapp",
    code: "https://github.com/adebayo-jzs/weatherapp",
    imgurl: "/weatherapp.jpg",
    type: "Website",
    year: 2025,
  },
];
