export const projects = [
  {
    id: 1,
    projectname: "Formpilot",
    slug:"formpilot",
    desc: "Framer website for Formpilot.Formpilot is an application for generating instant forms for surveys,feedback,bookings etc.",
    tools: [ "Framer"],
    preview: "https://formpilot.framer.website",
    // code: "https://github.com/adebayo-jzs/incognito",
    imgurl: "https://cdn.byteship.cloud/f/p_lZZewfvv/formpilot.png",
    type: "Framer Site",
    year: 2026,
  },
  {
    id: 2,
    projectname: "PageForge",
    slug:"pageforge",
    desc: "Transform your product ideas into high-conversion landing pages in seconds using Gemini AI. No coding required.",
    tools: ["NextJS","Typescript", "Tailwind", "Vanilla CSS", "MongoDB", "Node.js","Gemini API"],
    preview: "https://pageforge-nu.vercel.app",
    // code: "https://github.com/adebayo-jzs/incognito",
    imgurl: "https://cdn.byteship.cloud/f/p_lZZewfvv/pageforge.png",
    type: "Web Application",
    year: 2026,
  },
  {
    id: 3,
    projectname: "Focus Mode",
    slug:"focus-mode",
    desc: "Block distracting sites on demand. Stay in the zone.",
    tools: ["Javascript","CSS", "HTML"], 
    code: "https://github.com/adebayo-jzs/focus-mode",
    imgurl: "https://cdn.byteship.cloud/f/p_lZZewfvv/focus-mode.png",
    type: "Chrome extension",
    year: 2026,
  },
  {
    id: 4,
    projectname: "Quick notes",
    slug:"quick-notes",
    desc: "A per-site scratchpad that lives in your browser.",
    tools: ["Javascript","CSS", "HTML"], 
    code: "https://github.com/adebayo-jzs/quick-notes",
    imgurl: "https://cdn.byteship.cloud/f/p_lZZewfvv/quick-notes.png",
    type: "Chrome extension",
    year: 2026,
  },
  {
    id: 5,
    projectname: "Textcognito",
    slug: "textcognito",
    desc: "Textcognito is an anonymous messaging website where users can create unique links to receive anonymous messages from their friends.",
    tools: ["NextJS", "Tailwind", "Supabase", "Node.js"],
    preview: "https://textcognito.click",
    // code: "https://github.com/adebayo-jzs/incognito",
    imgurl: "https://cdn.byteship.cloud/f/p_lZZewfvv/textcognito.png",
    type: "Web Application",
    year: 2026,
  },
  {
    id: 6,
    projectname: "Arecnime",
    slug: "arecnime",
    desc: "Arecnime is an anime discovery and recommendation website designed to reimagine the anime browsing experience for anime lovers",
    tools: ["Tailwind", "React", "Javascript"],
    preview: "https://arecnime.vercel.app",
    // code: "https://github.com/adebayo-jzs/arecnime",
    imgurl: "https://cdn.byteship.cloud/f/p_lZZewfvv/anime.png",
    type: "Website",
    year: 2026,
  },
  {
    id: 8,
    projectname: "Fuelping",
    slug: "fuelping",
    desc: "Community-driven real-time fuel price updates at nearby stations in Nigeria",
    tools: ["React", "Typescript", "Tailwind", "Supabase"],
    preview: "https://fuelping.vercel.app",
    code: "https://github.com/adebayo-jzs/fuelping",
    imgurl: "https://cdn.byteship.cloud/f/p_lZZewfvv/fuelping.png",
    type: "Website",
    year: 2026,
  },
  {
    id: 9,
    projectname: "Personal Blog",
    slug: "personal-blog",
    desc: "Personal Developer blog built with supabase fully optimisized for Search Engines ",
    tools: ["React", "Tailwind", "Typescript", "Supabase"],
    preview: "https://blog.theebayo.name.ng",
    code: "https://github.com/adebayo-jzs/nextblog",
    imgurl: "https://cdn.byteship.cloud/f/p_lZZewfvv/blog.jpg",
    type: "Web Application",
    year: 2025,
  },

  {
    id: 10,
    projectname: "Basic Weather App",
    slug: "basic-weather-app",
    desc: "A basic weather app built with Open Weather API for checking 24 hours weather forecast for various locations ",
    tools: ["HTML", "CSS", "Javascript"],
    preview: "https://adebayo-jzs.github.io/weatherapp",
    code: "https://github.com/adebayo-jzs/weatherapp",
    imgurl: "https://cdn.byteship.cloud/f/p_lZZewfvv/weatherapp.jpg",
    type: "Website",
    year: 2025,
  },
];
